name: Deploy SSH

on:
  push:
    branches:
      - main

jobs:
  deploy-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_SSH_ID }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd <your-repository-directory>
            git reset --hard HEAD
            git pull
            <your-build-script>
            <your-process-restart-script>

# NOTICE: If cause under error
#
# `ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`
#
# You should add under contents in `/etc/ssh/sshd_config` file
#
# PubkeyAuthentication yes
# PubkeyAcceptedKeyTypes=+ssh-rsa
