name: Deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: touch dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # branch name
          folder: dist # generated folder name after build
          clean: true
