name: Deploy gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
          node-version: 16.x

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node-

      - run: pnpm install
        if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}

      - run: pnpm build
      - run: touch dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # branch name
          folder: dist # generated folder name after build
          clean: true
