name: Deploy Serverless AWS

on:
  push:
    branches:
      - dev

jobs:
  deploy-serverless-aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.2.2
          bun-config: '{"install": {"production": false}}'
          cache: true
          cache-bin: true

      - run: bun install
      - run: bun run build
      - run: bun serverless deploy --stage production -c serverless.yml"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}