name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.2.2
          bun-config: '{"install": {"production": true}}' # You may need to write false if necessary.
          cache: true
          cache-bin: true

      - run: bun install
      - run: bun run build

      - name: Push gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # branch name
          folder:  build # generated folder name after build
          clean: true
