name: Deploy Package

on:
  push:
    branches:
      - main

jobs:
  deploy-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
